FROM swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/rust:1.95.0-bookworm AS builder
WORKDIR /app
COPY Cargo.toml ./
COPY Cargo.lock ./
COPY crates ./crates
RUN cargo build --release -p sync_image_mcp

FROM debian:bookworm-slim
COPY --from=builder /app/target/release/sync-image-mcp /usr/local/bin/sync-image-mcp
ENTRYPOINT ["/usr/local/bin/sync-image-mcp"]
